In [1]:
import numpy as np
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten, MaxPooling3D, Conv3D, Dropout, BatchNormalization
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import ModelCheckpoint
import tensorflow as tf
import cv2
import sys
import time
from time import sleep
from cv2 import resize
import os
from tensorflow.keras.preprocessing import image

In [2]:
model = load_model("model(4).h5")

class_dict = {0: 'Closed', 1: 'Open', 2: 'no_yawn', 3: 'yawn'}

2021-11-04 15:05:15.670473: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-11-04 15:05:15.670703: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [10]:
# With help from https://www.opencvpython.online/2021/02/opencv-capture-image-from-camera.html

video_capture = cv2.VideoCapture(0)
count = 0


while True:
    
    start = time.time()
    
    if not video_capture.isOpened():
        print('Unable to load camera.')
        sleep(5)
        pass

    # Capture frame-by-frame
    ret, frame = video_capture.read()

    cv2.imwrite(f"Images/test/all_classes/_{count}.jpg", frame)
    count += 1

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
    
    test_image = resize(frame, (256,256))
    
    test_image = image.img_to_array(test_image)
    test_image = cv2.cvtColor(test_image, cv2.COLOR_BGR2GRAY)
    test_image = image.img_to_array(test_image)
    test_image = np.expand_dims(test_image, axis = 0)
    result = model.predict(test_image)
    
    pred = result.argmax(axis=-1)
    
    pred = [class_dict[x] for x in list(pred)]
    
    end = time.time()
    
    frame = cv2.putText(frame, pred[0], org = (100,200), fontFace = 1, fontScale = 5, color = [256,0,0])
    
    cv2.imshow('Video', frame)
    
    
    print("Seconds per frame: ", end-start)
    
# When everything is done, release the capture
video_capture.release()
cv2.destroyAllWindows()



Seconds per frame:  0.3073558807373047
Seconds per frame:  0.09030723571777344
Seconds per frame:  0.09831690788269043
Seconds per frame:  0.0987856388092041
Seconds per frame:  0.09851884841918945
Seconds per frame:  0.10275816917419434
Seconds per frame:  0.09678888320922852
Seconds per frame:  0.10093998908996582
Seconds per frame:  0.09678101539611816
Seconds per frame:  0.09919905662536621
Seconds per frame:  0.09470582008361816
Seconds per frame:  0.10542941093444824
Seconds per frame:  0.09682679176330566
Seconds per frame:  0.10079216957092285
Seconds per frame:  0.10048103332519531
Seconds per frame:  0.09738302230834961
Seconds per frame:  0.09747123718261719
Seconds per frame:  0.09929776191711426
Seconds per frame:  0.09767508506774902
Seconds per frame:  0.10093903541564941
Seconds per frame:  0.10373520851135254
Seconds per frame:  0.09473776817321777
Seconds per frame:  0.10696864128112793
Seconds per frame:  0.0910341739654541
Seconds per frame:  0.10161805152893066
Sec

In [ ]:
# with help from https://stackoverflow.com/questions/57656661/how-to-prediction-more-than-one-images-after-training-model-with-keras



datagen = ImageDataGenerator()

test_it = datagen.flow_from_directory('dataset_new 2/test', color_mode = "grayscale")
predict_it = datagen.flow_from_directory('Images/test', color_mode = "grayscale")

# test_image = image.load_img('Images/test/_0.jpg', target_size = (256, 256))
# test_image = image.img_to_array(test_image)
# test_image = cv2.cvtColor(test_image, cv2.COLOR_BGR2GRAY)
# test_image = image.img_to_array(test_image)
# test_image = np.expand_dims(test_image, axis = 0)
result = model.predict(predict_it)



In [9]:
print(result)

indices = {y:x for x,y in test_it.class_indices.items()}

[[7.06181567e-08 2.13788712e-06 1.02705389e-01 8.97292376e-01]
 [1.32898054e-10 1.11258949e-08 1.61258038e-02 9.83874202e-01]
 [1.40499409e-11 2.57288739e-11 3.76074940e-01 6.23925030e-01]
 [5.59327029e-10 1.01842386e-06 7.33737350e-02 9.26625252e-01]
 [7.59656560e-10 9.64334390e-07 9.43185762e-02 9.05680478e-01]
 [2.11515805e-10 1.71540449e-07 4.67057191e-02 9.53294039e-01]
 [7.15635745e-11 1.27035904e-09 5.36606967e-01 4.63393033e-01]
 [8.41770056e-12 1.06472051e-07 9.93096769e-01 6.90317061e-03]
 [5.30313293e-10 5.10032635e-07 5.52438684e-02 9.44755495e-01]
 [1.47368728e-10 9.55161639e-09 1.39671126e-02 9.86032903e-01]
 [1.96188861e-08 3.07787172e-06 3.39569338e-02 9.66039956e-01]
 [1.84562943e-09 2.00012650e-07 4.40154560e-02 9.55984235e-01]
 [2.18410331e-10 3.70809772e-07 5.94942532e-02 9.40505326e-01]
 [1.94839575e-10 3.26556702e-08 5.21275662e-02 9.47872460e-01]
 [1.32303423e-16 1.82819898e-10 9.60233569e-01 3.97663899e-02]
 [9.90176052e-10 6.58819715e-07 7.70300627e-02 9.229692

['yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'no_yawn', 'no_yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'no_yawn', 'yawn', 'no_yawn', 'yawn', 'yawn', 'no_yawn', 'yawn', 'yawn', 'no_yawn', 'no_yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'no_yawn', 'yawn', 'yawn', 'no_yawn', 'yawn', 'yawn', 'yawn', 'no_yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'no_yawn', 'yawn', 'yawn', 'yawn', 'no_yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'no_yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'no_yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'no_yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'yawn', 'y

In [13]:
# Eye detection with help from https://medium.com/@stepanfilonov/tracking-your-eyes-with-python-3952e66194a6

import cv2
import numpy
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('haarcascade_eye.xml')

{0: 'Closed', 1: 'Open', 2: 'no_yawn', 3: 'yawn'}
