In [2]:
import numpy as np
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten, MaxPooling3D, Conv3D, Dropout, BatchNormalization
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import ModelCheckpoint
import tensorflow as tf

In [3]:
model = load_model("model(4).h5")

2021-11-03 14:11:50.475524: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-11-03 14:11:50.476026: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [ ]:
import cv2
import sys
from time import sleep

video_capture = cv2.VideoCapture(0)
anterior = 0
count = 0


while True:
    if not video_capture.isOpened():
        print('Unable to load camera.')
        sleep(5)
        pass

    # Capture frame-by-frame
    ret, frame = video_capture.read()


    # Display the resulting frame
    cv2.imshow('Video', frame)

    cv2.imwrite(f"Images/test/all_classes/_{count}.jpg", frame)
    count += 1

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

    # Display the resulting frame
    cv2.imshow('Video', frame)
    
    
#     test_image = image.img_to_array(frame)
#     test_image = cv2.cvtColor(test_image, cv2.COLOR_BGR2GRAY)
#     test_image = image.img_to_array(test_image)
#     test_image = np.expand_dims(test_image, axis = 0)
#     result = model.predict(test_image)
    
#     print(result)
    
# When everything is done, release the capture
video_capture.release()
cv2.destroyAllWindows()



In [11]:
# with help from https://stackoverflow.com/questions/57656661/how-to-prediction-more-than-one-images-after-training-model-with-keras

import os
from tensorflow.keras.preprocessing import image

datagen = ImageDataGenerator()

test_it = datagen.flow_from_directory('dataset_new 2/test', color_mode = "grayscale")
predict_it = datagen.flow_from_directory('Images/test', color_mode = "grayscale")

# test_image = image.load_img('Images/test/_0.jpg', target_size = (256, 256))
# test_image = image.img_to_array(test_image)
# test_image = cv2.cvtColor(test_image, cv2.COLOR_BGR2GRAY)
# test_image = image.img_to_array(test_image)
# test_image = np.expand_dims(test_image, axis = 0)
result = model.predict(predict_it)



Found 433 images belonging to 4 classes.
Found 262 images belonging to 2 classes.


In [15]:
print(result)

indices = {y:x for x,y in test_it.class_indices.items()}

[[3.8876519e-01 2.3403715e-09 5.9927177e-01 1.1963053e-02]
 [3.6212010e-03 7.2831789e-11 9.9584705e-01 5.3175946e-04]
 [2.7395079e-01 7.5685280e-10 7.1731555e-01 8.7336302e-03]
 ...
 [3.6352634e-07 7.0199902e-14 9.9777126e-01 2.2284314e-03]
 [7.8227016e-04 1.3816263e-11 9.9538147e-01 3.8362821e-03]
 [3.0947501e-06 1.2799671e-10 9.6456182e-01 3.5435125e-02]]


In [13]:
pred = result.argmax(axis=-1)

In [19]:
pred = [indices[x] for x in list(pred)]

In [21]:
print(pred)

['no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'Closed', 'no_yawn', 'Closed', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 'no_yawn', 

In [22]:
# Eye detection with help from https://medium.com/@stepanfilonov/tracking-your-eyes-with-python-3952e66194a6

import cv2
import numpy
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('haarcascade_eye.xml')